<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>IdelPog.Messaging</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Validation\Validation.csproj"/>
    </ItemGroup>


    <ItemGroup>
        <InternalsVisibleTo Include="Messaging.Tests"/>
    </ItemGroup>

</Project>
