<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
	
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>IdelPogTests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\..\Shared\IdelPog.Infrastructure\IdelPog.Infrastructure.csproj" />
	  <ProjectReference Include="..\IdelPog.Infrastructure\IdelPog.Infrastructure.csproj" />
	  <ProjectReference Include="..\IdelPog.Validation\IdelPog.Validation.csproj" />
	</ItemGroup>

</Project>
