<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <RootNamespace>IdelPog.Frontend</RootNamespace>
        <OutputType>WinExe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.2.1105"/>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\Backend\IdelPog.ECS\IdelPog.ECS.csproj" />
      <ProjectReference Include="..\..\Shared\IdelPog.Common\IdelPog.Common.csproj" />
      <ProjectReference Include="..\..\Shared\IdelPog.Messaging\IdelPog.Messaging.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="UI\Service\" />
    </ItemGroup>
</Project>