<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IdelPog.Inventory</RootNamespace>
    <AssemblyName>IdelPog.Inventory</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core.csproj" />
    <ProjectReference Include="..\..\ECS\ECS.csproj" />
  </ItemGroup>
  
</Project>
